version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    restart: unless-stopped

  influxdb:
    build:
      context: .
      dockerfile: influxdb/Dockerfile
    image: influxdb_org:2.7
    container_name: influxdb
    ports:
      - "8087:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influxdb_admin_user
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb_admin_password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb_admin_token
      - DOCKER_INFLUXDB_INIT_ORG=default_org
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
    secrets:
      - influxdb_admin_user
      - influxdb_admin_password
      - influxdb_org
      - influxdb_bucket
      - influxdb_admin_token
    volumes:
      - influxdb-data:/var/lib/influxdb2  # Persistent data storage
      - influxdb-config:/etc/influxdb2   # Custom configuration files
      - influxdb1_data_volume-copy:/var/lib/influxdb
      - influxdb1_config_volume-copy:/etc/influxdb
    entrypoint: ["/bin/sh", "/custom-entrypoint.sh"]
    restart: unless-stopped

  influxdb1:
    image: influxdb:1.1.1
    container_name: influxdb1
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influxdb_admin_user
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb_admin_password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb_admin_token
      - DOCKER_INFLUXDB_INIT_ORG=default_org
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
    secrets:
      - influxdb_admin_user
      - influxdb_admin_password
      - influxdb_org
      - influxdb_bucket
      - influxdb_admin_token
    volumes:
      - influxdb1-data:/var/lib/influxdb  # Persistent data storage
      - influxdb1-config:/etc/influxdb   # Custom configuration files
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
      - nginx
    environment:
      - INFLUX_TOKEN_FILE=/run/secrets/influxdb_admin_token
    secrets:
      - influxdb_admin_token
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
    image: grafana/grafana_org:11.4.0
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - INFLUXDB_BUCKET=metrics
      - INFLUXDB_ORG=default_org
      - INFLUXDB_ADMIN_TOKEN__FILE=/run/secrets/influxdb_admin_token
    secrets:
      - grafana_admin_user
      - grafana_admin_password
      - influxdb_admin_token
      - influxdb_bucket
      - influxdb_org
    volumes:
      - grafana-data:/var/lib/grafana                    # For persistent data
      - grafana-provisioning:/etc/grafana/provisioning   # Provisioning in named volume
    entrypoint: ["/bin/sh", "/custom-entrypoint.sh"]
    restart: unless-stopped

volumes:
  influxdb-data:
    name: influxdb_data_volume
  influxdb-config:
    name: influxdb_config_volume
  influxdb1-data:
    name: influxdb1_data_volume
  influxdb1-config:
    name: influxdb1_config_volume
  grafana-data:
    name: grafana_data_volume
  grafana-provisioning:
    name: grafana_provisioning_volume
  influxdb1_data_volume-copy:
    name: influxdb1_data_volume-copy
  influxdb1_config_volume-copy:
    name: influxdb1_config_volume-copy

secrets:
  influxdb_admin_user:
    file: ./secrets/influxdb_admin_user
  influxdb_admin_password:
    file: ./secrets/influxdb_admin_password
  influxdb_org:
    file: ./secrets/influxdb_org
  influxdb_bucket:
    file: ./secrets/influxdb_bucket
  influxdb_admin_token:
    file: ./secrets/influxdb_admin_token
  grafana_admin_user:
    file: ./secrets/grafana_admin_user
  grafana_admin_password:
    file: ./secrets/grafana_admin_password
