apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      defaultBucket: ${INFLUXDB_BUCKET}
      organization: ${INFLUXDB_ORG}
      version: Flux
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
